import { useEffect, useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { track } from "~/lib/analytics";
export const Route=createFileRoute("/onboarding")({
  head: () => ({
    meta: [
      { title: "Set up your account — Before You Send" },
      { name: "description", content: "Tell us a little about your situation so your reviews and tools can be shaped around it." },
    ],
  }),
  component:Onboarding
});
const situations=["Co-parenting conflict","Custody dispute","Court process","Other"], helps=["Communication","Documentation","Organization","Action planning"];
function Onboarding(){const nav=useNavigate();const [authState,setAuthState]=useState<"checking"|"ready"|"error">("checking");const [authRetry,setAuthRetry]=useState(0);const [step,setStep]=useState(1);const [name,setName]=useState("");const [situation,setSituation]=useState<string[]>([]);const [help,setHelp]=useState<string[]>([]);const [err,setErr]=useState("");const [busy,setBusy]=useState(false);
// Auth gate (A1×B1, owner's auto-logout report 75fa1a07): same verdict/retry/
// catch contract as /home — redirect to "/" ONLY on a true no-session 401
// ({user:null} in the body); 5xx/network retries once after ~1.5s, then a calm
// in-page error with Retry instead of a redirect.
useEffect(()=>{let cancelled=false;const apply=async(r:Response):Promise<"ok"|"retry"|"gone">=>{if(r.status===401){const j=await r.json().catch(()=>({user:null}));return j&&j.user==null?"gone":"retry";}if(!r.ok)return "retry";return "ok"};const settle=(res:"ok"|"retry"|"gone")=>{if(res==="gone"){nav({to:"/"});return;}if(res==="retry"){setAuthState("error");return;}setAuthState("ready")};(async()=>{try{let res=await apply(await fetch("/api/auth/me"));if(res==="retry"){await new Promise(r2=>setTimeout(r2,1500));if(cancelled)return;res=await apply(await fetch("/api/auth/me"));}if(cancelled)return;settle(res);}catch{try{await new Promise(r2=>setTimeout(r2,1500));if(cancelled)return;settle(await apply(await fetch("/api/auth/me")));}catch{if(!cancelled)setAuthState("error");}}})();return ()=>{cancelled=true}},[authRetry]);
if(authState==="checking")return <main id="main" tabIndex={-1} className="mx-auto flex min-h-dvh max-w-lg items-center justify-center px-5"><div className="text-center"><div className="mx-auto h-9 w-9 animate-spin rounded-full border-2 border-forest/20 border-t-forest" aria-hidden="true"/><p className="mt-4 text-base text-stone">Loading…</p></div></main>;
if(authState==="error")return <main id="main" tabIndex={-1} className="mx-auto flex min-h-dvh max-w-lg items-center justify-center px-5"><div className="card w-full max-w-md p-7 text-center"><h1 className="font-display text-2xl font-semibold leading-snug text-forest">We couldn't reach the server — give it a moment.</h1><button type="button" onClick={()=>{setAuthRetry(n=>n+1);setAuthState("checking")}} className="btn-primary mt-6 w-full">Retry</button></div></main>;
async function next(){if(step<3){setStep(step+1);return}if(!name.trim()){setErr("Add your name to continue.");setStep(1);return}if(busy)return;setBusy(true);setErr("");try{const r=await fetch("/api/auth/profile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,situation,help})});if(!r.ok){setErr("We couldn't save that yet.");return}track("email_confirmed",{});await nav({to:"/home"})}catch{setErr("We couldn't save that yet.")}finally{setBusy(false)}}return <main id="main" tabIndex={-1} className="mx-auto min-h-dvh max-w-lg px-5 py-10"><header className="flex items-center justify-between"><a href="/" className="flex items-center gap-2 font-display text-2xl font-semibold text-forest"><img src="/logo-bys.svg" alt="" aria-hidden="true" className="h-7 w-7" />Before You Send<span className="text-forest-soft">.</span></a><span className="text-base text-stone">Step {step} of 3</span></header><div className="mt-16"><h1 className="font-display text-3xl font-semibold text-forest">Three quick questions.</h1>{step===1&&<label className="mt-8 block"><span className="field-label">What should we call you?</span><input autoFocus autoComplete="name" maxLength={60} value={name} onChange={e=>setName(e.target.value)} className="input" placeholder="Your name"/> </label>}{step===2&&<Choices title="What are you dealing with?" values={situations} selected={situation} set={setSituation}/>} {step===3&&<Choices title="What do you want help with?" values={helps} selected={help} set={setHelp}/>} {err&&<p role="alert" className="mt-4 text-base text-red-800">{err}</p>}<button onClick={next} disabled={busy} className="btn-primary mt-8 w-full">{busy?"Saving…":step===3?"Enter Command Center":"Continue"}</button>{step>1&&<button onClick={()=>setStep(step-1)} className="btn-ghost mt-3 w-full">Back</button>}</div></main>}
function Choices({title,values,selected,set}:{title:string;values:string[];selected:string[];set:(x:string[])=>void}){return <fieldset className="mt-8"><legend className="field-label">{title}</legend><div className="mt-3 space-y-3">{values.map(v=><label key={v} className="flex min-h-14 cursor-pointer items-center gap-3 rounded-xl border border-line bg-card px-4"><input type="checkbox" checked={selected.includes(v)} onChange={()=>set(selected.includes(v)?selected.filter(x=>x!==v):[...selected,v])} className="h-5 w-5 accent-forest"/><span className="text-base">{v}</span></label>)}</div></fieldset>}
