import { createFileRoute } from '@tanstack/react-router';
import { SiteFooter, SiteHeader } from "~/components/SiteChrome";
import { consultationMoney } from "~/lib/prices";
import { seoHead } from "~/lib/seo";

const pages = {
  about: {eyebrow:'Who we are', title:"We're the pause before the message that matters.", body:<><p>Before You Send started with the moment every co-parent knows: the message that feels earned at 11pm would be better sent calmly in the morning.</p><p>We built a practical read on your words and three calm rewrites. The Command Center keeps communication and important events organized so you can focus on being a dad.</p><h2>What we do</h2><ul><li>Message Review: Gentle, Direct, and Firm but Neutral rewrites.</li><li>Communication Log, Event Timeline, Document Organizer, Case Summary, Action Center, and the Export pack are live.</li><li>A 45-minute perspective consultation is {consultationMoney}, one time, not legal advice.</li></ul><p>We do not invent testimonials, promise outcomes, or create pressure. Before You Send is not a law firm and does not provide legal advice.</p></>},
  trust: {eyebrow:'Trust', title:'What you can count on.', body:<><h2>Honest by design</h2><p>No invented testimonials, no promised outcomes, no fake deadlines or scarcity, and no pressure tactics. If something is new, we say so. If it's limited, it's limited for a real reason — like 5 free reviews a month.</p><h2>Real prices, real caps</h2><ul><li>Free: first review free; with an account, 5 reviews/month and the last 10 saved.</li><li>Steady: $4.99/month or $49.90 annual; 30 reviews/month and unlimited saved history.</li><li>Command Center: $12.49/month or $124.90 annual; unlimited reviews plus the live Document Organizer, Case Summary, and Action Center.</li><li>Ultimate Co-Parent: $24.99/month or $249.90 annual; everything we offer, including consultation benefits and packs.</li></ul><p>Annual billing is 10 months billed yearly. A consultation is {consultationMoney} for 45 minutes, one time. Review Top-Up is $9.50 for 10 credits.</p><h2>Your privacy</h2><p>Drafts and reviews are processed to give you your rewrites and are not sold or used for advertising. The full details are on the Privacy page.</p><h2>What this is</h2><p>Communication guidance and organization — not a law firm, not legal advice, and not a promise of any legal outcome.</p></>},
  privacy: {eyebrow:'Privacy', title:'Your drafts stay yours.', body:<><p>We collect drafts and reviews you submit, your email and account details, Communication Log and Timeline entries, session cookie, and basic funnel analytics. Analytics receive event labels and coarse usage signals — never your draft text, situation answers, children's details, or payment identifiers.</p><p>If you use the Co-Parent Check-In, your three answers are used to match you to a plan and to improve the product.</p><h2>How data is handled</h2><p>Reviews are processed by SambaNova using DeepSeek-V3.2 — a third-party AI provider. Account data, drafts, reviews, logs, and timeline entries are stored in Neon Postgres. Payments are processed by Stripe; we never store card numbers. We never sell your data, and we never use your drafts or situation answers for advertising.</p><p>For ad measurement we work with Google Ads and TikTok. Basic, non-sensitive usage events (like page views and checkout starts) may be shared with those providers, and the email you provide at signup may be used for conversion matching where that is enabled and you have consented. Your draft text, situation answers, and children's details are never sent to advertising platforms.</p><p>Anonymous reviews are processed but are not saved to an account. We retain account data until you ask us to delete it. Email <a href="mailto:before-you-send-615d3704@ctomail.io">support</a> from your account address with “Delete my account.” If you have an active paid subscription, it is cancelled before your account is deleted. If the cancellation cannot be confirmed, deletion is refused and you are directed to Manage subscription first.</p><p>This is not a confidential legal channel and stored data is not attorney-client privileged. Do not submit passwords, financial numbers, or sensitive information you do not want processed.</p><p>We use a secure HttpOnly session cookie and may use Google Ads and TikTok analytics cookies. Questions: <a href="mailto:before-you-send-615d3704@ctomail.io">email us</a>.</p></>},
  terms: {eyebrow:'Terms', title:'Clear terms for a practical service.', body:<><h2>Plans</h2><ul><li>Free: first review free; free account includes 5 reviews/month, last 10 saved reviews, and unlimited Log and Timeline.</li><li>Steady: $4.99/month or $49.90 annual; 30 reviews/month and unlimited saved history.</li><li>Command Center: $12.49/month or $124.90 annual; unlimited reviews, and the live Document Organizer, Case Summary, Action Center, and Export pack.</li><li>Ultimate Co-Parent: $24.99/month or $249.90 annual; Command Center benefits plus included one-time packs and consultation benefits.</li></ul><p>Annual billing is 10 months billed yearly. Consultation is {consultationMoney} for 45 minutes, one time. Review Top-Up is $9.50 for 10 credits.</p><h2>Billing and cancellation</h2><p>Subscriptions renew through Stripe until you cancel. You can manage or cancel your subscription anytime from the account’s Manage subscription button; Stripe’s billing portal handles cancellation, payment methods, and invoices. Access continues through the paid period; unused time is not refunded.</p><p>The service is communication guidance and organization, not legal advice, therapy, or a promise of any custody or legal outcome. You own your submitted content. Use the service lawfully and do not submit secrets or privileged material.</p><p>Questions about billing or these terms: <a href="mailto:before-you-send-615d3704@ctomail.io">Email us</a>.</p></>},
  faq: {eyebrow:'FAQ', title:'Straight answers.', body:<><h2>Is this legal advice?</h2><p>No. It is communication guidance and organization, not a law firm or legal opinion.</p><h2>Can I cancel?</h2><p>Yes. Paid members can use Manage subscription in the account to open Stripe’s billing portal and cancel without a phone call. Access continues through the paid period.</p><h2>What are the plans?</h2><p>Free; Steady $4.99/month ($49.90 annual); Command Center $12.49/month ($124.90 annual); Ultimate Co-Parent $24.99/month ($249.90 annual). Annual billing is 10 months billed yearly.</p><h2>What is saved?</h2><p>Free accounts save the last 10 reviews and get 5 reviews/month. Steady saves unlimited history; Command Center and Ultimate include unlimited reviews and their listed tools.</p><h2>What else can I buy?</h2><p>A {consultationMoney} consultation is one time. Review Top-Up is $9.50 for 10 credits. Ultimate includes one-time packs and consultation benefits as described at checkout.</p><h2>How is data handled?</h2><p>SambaNova processes reviews; Neon Postgres stores account data; Stripe processes payments. We do not sell drafts. Stored data is not attorney-client privileged.</p></>},
  contact: {eyebrow:'Contact', title:'Talk to a real person.', body:<><p>Email <a href="mailto:before-you-send-615d3704@ctomail.io">before-you-send-615d3704@ctomail.io</a> for account questions, billing, cancellation, refunds, deletion, or feedback.</p><p>Include the account email and a short description (for billing: the plan and approximate signup date). We aim to respond within one business day.</p><p>This is product support, not an emergency line.</p></>}
} as const;
export function TrustPage({ kind, active = "other" }: { kind: keyof typeof pages; active?: string }) {
  const p = pages[kind];
  return (
    <div className="min-h-dvh bg-cream">
      <SiteHeader active={active} />
      <main id="main" tabIndex={-1} className="mx-auto max-w-2xl px-5 py-10 sm:py-14">
        <p className="text-sm font-semibold uppercase tracking-[.16em] text-forest-soft">{p.eyebrow}</p>
        <h1 className="mt-3 font-display text-4xl font-semibold leading-tight text-ink">{p.title}</h1>
        <div className="mt-8 border-t border-line pt-8">
          <article className="prose max-w-none space-y-5 text-base leading-relaxed text-ink">{p.body}</article>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
export const Route = createFileRoute('/trust')({
  head: () => ({
    ...seoHead({
      title: "Trust — Before You Send",
      description: "What you can count on: honest pricing, no invented testimonials, no pressure, and no fake deadlines. Your drafts stay private. Not legal advice.",
      path: "/trust",
    }),
  }),
  component:()=> <TrustPage kind="trust"/>
});
